/* xia_version.h -- DO NOT MODIFY
 *
 * This file automatically generated by 
 * build_helpers.version on 2025-02-13 16:24:44.675441
 */

#ifndef __XIA_VERSION_H__
#define __XIA_VERSION_H__

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 3
#define XERXES_RELEASE_VERSION 0

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 3
#define HANDEL_RELEASE_VERSION 0

#define VERSION_STRING "development"

#endif /* __XIA_VERSION_H__ */

