/* xia_version.h -- DO NOT MODIFY
 *
 * This file automatically generated by 
 * build_helpers.version on 2015-04-09 19:10:02.764000
 */

#ifndef __XIA_VERSION_H__
#define __XIA_VERSION_H__

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 2
#define XERXES_RELEASE_VERSION 2

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 2
#define HANDEL_RELEASE_VERSION 2

#define VERSION_STRING "release"

#endif /* __XIA_VERSION_H__ */

