/* xia_version.h -- DO NOT MODIFY
 *
 * This file automatically generated by 
 * build_helpers.version on 2017-08-29 16:24:46.284000
 */

#ifndef __XIA_VERSION_H__
#define __XIA_VERSION_H__

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 2
#define XERXES_RELEASE_VERSION 16

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 2
#define HANDEL_RELEASE_VERSION 16

#define VERSION_STRING "development"

#endif /* __XIA_VERSION_H__ */

